<?php
/**
 * SettlementEventSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Transaction API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SettlementEventSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description SettlementEventSummary
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettlementEventSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SettlementEventSummary"
     */
    public function testSettlementEventSummary()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "deposit_id"
     */
    public function testPropertyDepositId()
    {
    }

    /**
     * Test attribute "total_sales"
     */
    public function testPropertyTotalSales()
    {
    }

    /**
     * Test attribute "total_refunds"
     */
    public function testPropertyTotalRefunds()
    {
    }

    /**
     * Test attribute "total_fees"
     */
    public function testPropertyTotalFees()
    {
    }

    /**
     * Test attribute "total_settled"
     */
    public function testPropertyTotalSettled()
    {
    }

    /**
     * Test attribute "account_last_four"
     */
    public function testPropertyAccountLastFour()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }
}
