<?php
/**
 * TransactionsAPIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Transaction API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TransactionsAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsAPIApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for authorizeTransaction
     *
     * Authorize Transaction.
     *
     */
    public function testAuthorizeTransaction()
    {
    }

    /**
     * Test case for captureTransaction
     *
     * Capture Transaction.
     *
     */
    public function testCaptureTransaction()
    {
    }

    /**
     * Test case for listSettlementEventSummaries
     *
     * List Settlement Event Summaries.
     *
     */
    public function testListSettlementEventSummaries()
    {
    }

    /**
     * Test case for listSettlementEvents
     *
     * List Settlement Events.
     *
     */
    public function testListSettlementEvents()
    {
    }

    /**
     * Test case for listTransactionEvents
     *
     * List Transaction Events.
     *
     */
    public function testListTransactionEvents()
    {
    }

    /**
     * Test case for listTransactions
     *
     * List Transactions.
     *
     */
    public function testListTransactions()
    {
    }

    /**
     * Test case for readTransaction
     *
     * Read Transaction.
     *
     */
    public function testReadTransaction()
    {
    }

    /**
     * Test case for refundTransaction
     *
     * Refund Transaction.
     *
     */
    public function testRefundTransaction()
    {
    }

    /**
     * Test case for updateTransaction
     *
     * Update Transaction.
     *
     */
    public function testUpdateTransaction()
    {
    }

    /**
     * Test case for voidTransaction
     *
     * Void Transaction.
     *
     */
    public function testVoidTransaction()
    {
    }
}
